baseurl: "http://www.unstdout.io"
publishdir: "../public"
title: "unstdout"
canonifyurls: true
permalinks:
  post: /:year/:month/:day/:slug/
params:
  GaTrackingID: "UA-70947-16"
  GaCookieDomain: "unstdout.io"
